const THIRD_PARTY_HEADER_PATTERNS = [
  /@license/i,
  /copyright \(c\)/i,
  /generated by webpack/i,
  /webpackbootstrap/i,
  /for license information please see/i,
  /jquery v\d+/i,
  /lodash/i,
  /react production minified/i,
  /vue\.runtime/i,
  /angularjs v\d+/i,
  /bootstrap v\d+/i,
];

const THIRD_PARTY_PATH_PATTERNS = [
  /(^|\/)(vendor|vendors|third_party|external|deps)(\/|$)/i,
  /(^|\/)(dist|build|out)(\/|$)/i,
];

export function hasThirdPartyPathSignature(path) {
  const text = String(path || "");
  return THIRD_PARTY_PATH_PATTERNS.some((regex) => regex.test(text));
}

export function hasThirdPartyContentSignature(content) {
  const head = String(content || "").slice(0, 3000);
  let hitCount = 0;

  for (const pattern of THIRD_PARTY_HEADER_PATTERNS) {
    if (pattern.test(head)) hitCount += 1;
  }

  return hitCount >= 2;
}

export function isLikelyThirdPartyCode({ path, content }) {
  if (hasThirdPartyPathSignature(path)) return true;
  return hasThirdPartyContentSignature(content);
}
